---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/argocd version --client
    register: argocd_test_output
  - name: argocd version --client
    debug:
      msg: '{{ argocd_test_output.stdout }}'
