---
- name: Testing andrewrothstein.argocd
  hosts: all
  tasks:
    - name: Installing andrewrothstein.argocd
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
    - name: Executing 'argocd version --client'
      ansible.builtin.command: /usr/local/bin/argocd version --client
      changed_when: false
      register: argocd_test_output
    - name: Output of 'argocd version --client'
      ansible.builtin.debug:
        msg: '{{ argocd_test_output.stdout }}'
