---
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Downloading {{ argocd_url }} to {{ argocd_exe }}
  become: true
  become_user: root
  ansible.builtin.get_url:
    url: '{{ argocd_url }}'
    dest: '{{ argocd_exe }}'
    checksum: '{{ argocd_checksum }}'
    mode: '755'
- name: Linking {{ argocd_link }} to {{ argocd_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ argocd_exe }}'
    dest: '{{ argocd_link }}'
    state: link
